server:
  port: 7001

spring:
  application:
    naem: springcloud-eureka-server  # 服务模块名称
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root

# Eureka配置
eureka:
  instance:
    hostname: localhost
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    register-with-eureka: false # 表示是否向Eureka注册自己
    fetch-registry: false # false表示自己为注册中心
    service-url:  # 监控页面地址 默认 this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");
      defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS